export const TOGGLE_MENU      = 'app/header/toggle'

export const MOUNT_VIDEO      = 'home/video/mount'
export const MOUNT_SUCCESS    = 'home/video/loaded'
export const MOUNT_ERROR      = 'home/video/error'
export const ABORT_MOUNT      = 'home/video/abort'
export const PLAY_NEXT        = 'home/video/next'
export const UNMOUNT_VIDEO    = 'home/video/unmount'
export const VIDEO_PLAYING    = 'home/video/playing'
export const VIDEO_ENDED      = 'home/video/ended'
export const FADE_LOADER      = 'home/video/loader/fade'
export const HIDE_LOADER      = 'home/video/loader/hide'

export const MOUNT_CAROUSEL   = 'projects/carousel/load'
export const NEXT_SLIDE       = 'projects/carousel/next'
export const UNMOUNT_CAROUSEL = 'projects/carousel/unmount'
